## Домашнее задание «Библиотека numpy. Вычислительные задачи»

### Задание 1

In [ ]:
"""
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
"""

In [69]:
import numpy as np
N = int(input())
array = np.linspace(N, 0, num = N + 1, endpoint = True, dtype=int)
array

10


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2

In [ ]:
"""
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
"""

In [46]:
import numpy as np
N = int(input())
array = np.linspace(N, 0, num = N + 1, endpoint = True, dtype=int)
diag_array = np.diag(array)
print(diag_array)
np.sum(array)

10
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]


55

### Задание 3

In [ ]:
"""
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""

In [61]:
import numpy as np
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

In [119]:
import numpy as np
import matplotlib.pyplot as plt
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
"""
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
"""
all_angle = []
for user in users_stats:
    aLength = np.linalg.norm(user)
    bLength = np.linalg.norm(next_user_stats)
    angle = np.array(np.arccos(np.dot(user, next_user_stats ) / (aLength * bLength)) * 360 / 2 / np.pi)
    all_angle.append(angle)
    print(angle)
    
print('Минимальный угол между пользователями:', min(all_angle))

78.46304096718453
32.311533237423866
66.42182152179818
37.761243907035045
66.42182152179818
90.0
90.0
18.434948822922017
90.0
90.0
Минимальный угол между пользователями: 18.434948822922017
